// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu5UamO64u-7t37GqgSXIq1RvkXS3CVRc',
    appId: '1:577480287388:web:ea9ed1891a017185083959',
    messagingSenderId: '577480287388',
    projectId: 'bright-bike-rentals',
    authDomain: 'bright-bike-rentals.firebaseapp.com',
    storageBucket: 'bright-bike-rentals.appspot.com',
    measurementId: 'G-WF8VNR8W2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlDAGq5iG_Drf5XGoMK57qN7cx2subDDc',
    appId: '1:577480287388:android:d84ba23420246e97083959',
    messagingSenderId: '577480287388',
    projectId: 'bright-bike-rentals',
    storageBucket: 'bright-bike-rentals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsogXy-wvdf0nosw2AfBa_4ifXP12RVJA',
    appId: '1:577480287388:ios:7f9767481d2b8a27083959',
    messagingSenderId: '577480287388',
    projectId: 'bright-bike-rentals',
    storageBucket: 'bright-bike-rentals.appspot.com',
    iosBundleId: 'com.example.brightBikeRentals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsogXy-wvdf0nosw2AfBa_4ifXP12RVJA',
    appId: '1:577480287388:ios:7f9767481d2b8a27083959',
    messagingSenderId: '577480287388',
    projectId: 'bright-bike-rentals',
    storageBucket: 'bright-bike-rentals.appspot.com',
    iosBundleId: 'com.example.brightBikeRentals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBu5UamO64u-7t37GqgSXIq1RvkXS3CVRc',
    appId: '1:577480287388:web:07cfa8dc8a475dd4083959',
    messagingSenderId: '577480287388',
    projectId: 'bright-bike-rentals',
    authDomain: 'bright-bike-rentals.firebaseapp.com',
    storageBucket: 'bright-bike-rentals.appspot.com',
    measurementId: 'G-YLMLPWRP9S',
  );
}
